## Task 1: Text Cleaning

In this activity, we create a function that takes a paragraph and returns a cleaned list of words.

The words are:
- converted to lowercase
- stripped of leading and trailing punctuation
- returned as a list

In [13]:
paragraph ='''  Hey My name is Noor Zahid.
I am a Data Science Student in 6th semester. 
I am doing my Bachelors from Comsats University Islamabad  '''

In [26]:
def cleanData(data):
    lowercased = data.lower()
    strippedSPaces = lowercased.strip()
    words = strippedSPaces.split()

    return words

In [27]:
cleanData(paragraph)

['hey',
 'my',
 'name',
 'is',
 'noor',
 'zahid.',
 'i',
 'am',
 'a',
 'data',
 'science',
 'student',
 'in',
 '6th',
 'semester.',
 'i',
 'am',
 'doing',
 'my',
 'bachelors',
 'from',
 'comsats',
 'university',
 'islamabad']

# Task 2 — Top 10 Most Frequent Words
In this activity, we use Counter to count how many times each word appears in an article.

We then display the 10 most frequent words and their counts.

In [30]:
from collections import Counter

article = """
Python is a popular programming language.
Python is used for data science and machine learning.
Data science uses Python for analysis and visualization.
"""

words = article.lower().split()

word_counts = Counter(words)

top_10 = word_counts.most_common(10)

print("Word\t\tCount")
print("----\t\t-----")

for word, count in top_10:
    print(f"{word}\t\t{count}")

Word		Count
----		-----
python		3
is		2
for		2
data		2
science		2
and		2
a		1
popular		1
programming		1
language.		1

## Activity 3: Sentence-Level DataFrame

In this activity, we split a paragraph into individual sentences and create a DataFrame.

Each row represents one sentence.

We calculate:
- word_count: number of words in the sentence
- char_count: number of characters in the sentence

The .apply() function is used to calculate these values.

In [32]:
import pandas as pd

paragraph = """
Python is easy to learn. 
It is widely used in data science. 
Students can use Python for many different projects.
"""

sentences = paragraph.strip().split(".")

sentences = [sentence.strip() for sentence in sentences if sentence.strip()]

df = pd.DataFrame({"sentence": sentences})

df["word_count"] = df["sentence"].apply(lambda x: len(x.split()))
df["char_count"] = df["sentence"].apply(lambda x: len(x))

df

                                            sentence  word_count  char_count
0                            Python is easy to learn           5          23
1                  It is widely used in data science           7          33
2  Students can use Python for many different pro...           8          51

## Task 4: Cosine Similarity

Cosine similarity measures how similar two vectors are.

The formula is:

Cosine Similarity = (A · B) / (||A|| × ||B||)

where:
- A · B is the dot product
- ||A|| is the magnitude of vector A
- ||B|| is the magnitude of vector B

A value closer to 1 means the vectors are more similar.
A value closer to 0 means the vectors are less similar.

NumPy is used to perform the calculations.

In [33]:
import numpy as np

A1 = np.array([1, 2, 3])
B1 = np.array([1, 2, 2])

A2 = np.array([1, 0, 3])
B2 = np.array([0, 2, 1])

In [34]:
def cosine_similarity(A, B):
    dot_product = np.dot(A, B)
    
    magnitude_A = np.linalg.norm(A)
    magnitude_B = np.linalg.norm(B)
    
    similarity = dot_product / (magnitude_A * magnitude_B)
    
    return similarity

In [35]:
similarity_1 = cosine_similarity(A1, B1)
similarity_2 = cosine_similarity(A2, B2)

print("Pair 1:", similarity_1)
print("Pair 2:", similarity_2)

Pair 1: 0.9799578870122228
Pair 2: 0.42426406871192845

### Conclusion

Pair 1 is more similar because its cosine similarity value is higher than Pair 2.

A higher cosine similarity means that the two word-count vectors have a more similar direction.

## Task 5: Review Analysis Using JSON and Counter

In this activity, we load a JSON file containing 10 short reviews.

We:
1. Load the JSON file.
2. Convert the reviews into a DataFrame.
3. Calculate the word count of each review.
4. Use Counter to find the most frequent word in each review.
5. Add the most frequent word as a new column.
6. Sort the DataFrame by word_count in descending order.

In [47]:
import json
import pandas as pd
from collections import Counter
import string

with open("reviews.json", "r") as file:
    data = json.load(file)

df = pd.DataFrame(data)

df.head()

,_id,author,store,text,rating,created
0,58c03ac18060197ca0b52d51,58c039018060197ca0b52d4c,58c03a958060197ca0b52d50,I tried this place last week and it was incred...,5,2017-03-08T17:09:21.627Z
1,58c03af28060197ca0b52d53,58c03ada8060197ca0b52d52,58c03a958060197ca0b52d50,hipsters everywhere,1,2017-03-08T17:10:10.426Z
2,58c08780bbb1a51e0d43a050,58c039018060197ca0b52d4c,58c065dbbbb1a51e0d43a04f,Always a great spot to grab a coffee with a fr...,5,2017-03-08T22:36:48.575Z
3,58c08796bbb1a51e0d43a051,58c039018060197ca0b52d4c,58c061518060197ca0b52d5e,"Great ramen, a little pricey for what you get.",3,2017-03-08T22:37:10.483Z
4,58c087acbbb1a51e0d43a052,58c039018060197ca0b52d4c,58c060e98060197ca0b52d5d,Tried this place with my wife last week and it...,4,2017-03-08T22:37:32.829Z

In [49]:
df["word_count"] = df["text"].apply(lambda x: len(x.split()))

df.head()

,_id,author,store,text,rating,created,word_count
0,58c03ac18060197ca0b52d51,58c039018060197ca0b52d4c,58c03a958060197ca0b52d50,I tried this place last week and it was incred...,5,2017-03-08T17:09:21.627Z,24
1,58c03af28060197ca0b52d53,58c03ada8060197ca0b52d52,58c03a958060197ca0b52d50,hipsters everywhere,1,2017-03-08T17:10:10.426Z,2
2,58c08780bbb1a51e0d43a050,58c039018060197ca0b52d4c,58c065dbbbb1a51e0d43a04f,Always a great spot to grab a coffee with a fr...,5,2017-03-08T22:36:48.575Z,11
3,58c08796bbb1a51e0d43a051,58c039018060197ca0b52d4c,58c061518060197ca0b52d5e,"Great ramen, a little pricey for what you get.",3,2017-03-08T22:37:10.483Z,9
4,58c087acbbb1a51e0d43a052,58c039018060197ca0b52d4c,58c060e98060197ca0b52d5d,Tried this place with my wife last week and it...,4,2017-03-08T22:37:32.829Z,12

In [51]:
def top_word(review):
    words = review.lower().split()
    
    cleaned_words = []
    
    for word in words:
        word = word.strip(string.punctuation)
        cleaned_words.append(word)
    
    counts = Counter(cleaned_words)
    
    return counts.most_common(1)[0][0]

df["top_word"] = df["text"].apply(top_word)

df.head()

,_id,author,store,text,rating,created,word_count,top_word
0,58c03ac18060197ca0b52d51,58c039018060197ca0b52d4c,58c03a958060197ca0b52d50,I tried this place last week and it was incred...,5,2017-03-08T17:09:21.627Z,24,and
1,58c03af28060197ca0b52d53,58c03ada8060197ca0b52d52,58c03a958060197ca0b52d50,hipsters everywhere,1,2017-03-08T17:10:10.426Z,2,hipsters
2,58c08780bbb1a51e0d43a050,58c039018060197ca0b52d4c,58c065dbbbb1a51e0d43a04f,Always a great spot to grab a coffee with a fr...,5,2017-03-08T22:36:48.575Z,11,a
3,58c08796bbb1a51e0d43a051,58c039018060197ca0b52d4c,58c061518060197ca0b52d5e,"Great ramen, a little pricey for what you get.",3,2017-03-08T22:37:10.483Z,9,great
4,58c087acbbb1a51e0d43a052,58c039018060197ca0b52d4c,58c060e98060197ca0b52d5d,Tried this place with my wife last week and it...,4,2017-03-08T22:37:32.829Z,12,tried

### Sorting the Reviews

Finally, I sorted the DataFrame by word_count in descending order so that the reviews with the highest number of words appear first.

In [54]:
# sort
df = df.sort_values("word_count", ascending=False)

df.head(10)

,_id,author,store,text,rating,created,word_count,top_word
0,58c03ac18060197ca0b52d51,58c039018060197ca0b52d4c,58c03a958060197ca0b52d50,I tried this place last week and it was incred...,5,2017-03-08T17:09:21.627Z,24,and
6,58c087debbb1a51e0d43a054,58c039018060197ca0b52d4c,58c060558060197ca0b52d5b,If you need a great place with bangin' food th...,5,2017-03-08T22:38:22.858Z,18,if
26,58c08aa1d1d97c276fd56ce0,58c03ada8060197ca0b52d52,58c05b558060197ca0b52d56,I ate at this place and I had two black someth...,1,2017-03-08T22:50:09.568Z,14,i
10,58c08832bbb1a51e0d43a058,58c039018060197ca0b52d4c,58c05bcd8060197ca0b52d57,I only wish I could find them before they were...,3,2017-03-08T22:39:46.011Z,13,i
39,58c6a8f6fb4d61115815f8b8,58c08bbed1d97c276fd56ce3,58c05aef8060197ca0b52d55,I could eat these tacos every day for the rest...,4,2017-03-13T14:13:10.681Z,13,i
14,58c08878bbb1a51e0d43a05c,58c039018060197ca0b52d4c,58c03a428060197ca0b52d4f,I'm not a fancy dude but this place is the cat...,5,2017-03-08T22:40:56.312Z,12,i'm
33,58c6a853fb4d61115815f8b2,58c08bbed1d97c276fd56ce3,58c060558060197ca0b52d5b,Nothing better than a PBR after a long day of ...,3,2017-03-13T14:10:27.885Z,12,a
4,58c087acbbb1a51e0d43a052,58c039018060197ca0b52d4c,58c060e98060197ca0b52d5d,Tried this place with my wife last week and it...,4,2017-03-08T22:37:32.829Z,12,tried
2,58c08780bbb1a51e0d43a050,58c039018060197ca0b52d4c,58c065dbbbb1a51e0d43a04f,Always a great spot to grab a coffee with a fr...,5,2017-03-08T22:36:48.575Z,11,a
23,58c08a58d1d97c276fd56cdd,58c03ada8060197ca0b52d52,58c05f928060197ca0b52d59,Now this is a place that I can get behind!,5,2017-03-08T22:48:56.600Z,10,now

In [56]:
df[["text", "word_count", "top_word", "rating"]].head(10)

,text,word_count,top_word,rating
0,I tried this place last week and it was incred...,24,and,5
6,If you need a great place with bangin' food th...,18,if,5
26,I ate at this place and I had two black someth...,14,i,1
10,I only wish I could find them before they were...,13,i,3
39,I could eat these tacos every day for the rest...,13,i,4
14,I'm not a fancy dude but this place is the cat...,12,i'm,5
33,Nothing better than a PBR after a long day of ...,12,a,3
4,Tried this place with my wife last week and it...,12,tried,4
2,Always a great spot to grab a coffee with a fr...,11,a,5
23,Now this is a place that I can get behind!,10,now,5